#!/bin/bash
#------- NUNCA: ------#
# Nunca pongas aqui wal -R porque sino se ejecutara a cada rato entrando en bucle

export PATH="$PATH:$HOME/.config/bspwm/scripts"

export PATH="$PATH:$HOME/.config/dunst/scripts"

export PATH="$PATH:$HOME/.config/polybar/scripts"

setup &

#------- Notificar actualizaciones de paquetes y estado de la bateria -------#
update_pacman.sh &

detectar_pantalla_completa.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         6
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

# usar variables de color actualizadas
. "${HOME}/.cache/wal/colors.sh"

bspc config focus_follows_pointer true
bspc config focused_border_color "$color5"
bspc config presel_feedback_color "$color5"

picom -b &

#----------------------------Configuracion de monitores con sd-------------------------------#
bspc monitor  -d I II III IV V VI VII VIII IX X
bspc monitor  -o I II III IV V VI VII VIII IX X
