include-file = colors.ini
include-file = modules.ini
include-file = decor.ini

[bar/main]
override-redirect = false
wm-restack = bspwm
enable-ipc = true
font-0 = Terminus (TTF):style=Medium:pixelsize=12;3
font-1 = Iosevka Nerd Font:style=Medium:size=25;6
font-2 = Hack Nerd Font:style=Regular:pixelsize=16;3
font-3 = Iosevka Nerd Font:style=Medium:size=16;3
font-4 = Iosevka Nerd Font:style=Regular:pixelsize=16;3

line-size = 3pt
border-size = 0pt
border-color = #000000
module-margin-left = 0
module-margin-right = 0
cursor-click = pointer
cursor-scroll = ns-resize
separator = "|"
separator-foreground = ${colors.transparent}
separator-margin = 1

[bar/barup]
inherit = bar/main
top = true
width = 100%
height = 4%
radius = 0
padding-right = 2
padding-left = 2
margin-top = 0
background = ${colors.background-alt}
foreground = ${colors.foreground}
modules-left = xwindow wireless bluetooth
modules-center = left-cut xworkspaces right-cut
modules-right = cava control volume date notification battery 

[bar/bardown]
inherit = bar/main
separator = ""
bottom = true
width = 100%
height = 3%
radius = 0
; Necesariamente usar la variable colors.transparent de colors.ini para que sea transparente el espacio entre las dos partes de la barra de abajo
background = ${colors.transparent}
foreground = ${colors.foreground}
modules-left = htb left-decor 
modules-center =     
modules-right = right-decor memory storage 

[settings]
screenchange-reload = true
pseudo-transparency = true
