[module/htb]
type = custom/script
tail = true
label-padding = 1
format = <label>
format-foreground = ${colors.foreground}
exec = ~/.config/polybar/scripts/hackthebox_status.sh

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh --status
interval = 1
click-left = ~/.config/polybar/scripts/bluetooth.sh &
label-foreground = ${colors.foreground}

[module/notification]
type = custom/ipc
hook-0 = echo "$(dunstctl set-paused true)%{T3}%{T-}"
hook-1 = echo "$(dunstctl set-paused false)%{T3}%{T-}" 
initial = 2
click-left = "#notification.hook.0"
click-right = "#notification.hook.1"
format-padding = 1 

[module/xworkspaces]
type = internal/xworkspaces
icon-default = %{T4}󰊠 %{T-}
label-active = %{T4}󰮯 %{T-}
label-active-background = ${colors.background-alt}
label-active-foreground = ${colors.active}
label-active-padding = 1

label-occupied = %icon% 
label-occupied-padding = 1
label-occupied-foreground = ${colors.selected}
label-occupied-background = ${colors.background-alt}

label-urgent = %icon%
label-urgent-background = ${colors.background-alt}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background-alt}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
format = <label>
format-foreground= ${colors.foreground}
label-padding = 1
label-maxlen = 20

[module/control]
type = custom/script
tail = true
label-padding = 1
label-foreground = ${colors.foreground}
exec = pulseaudio-control --icons-volume "%{T5}󰕿%{T-},%{T5}%{T-},%{T5} %{T-}" --icon-muted "󰝟 "/ --node-nickname "alsa_output.pci-0000_00_1b.0.analog-stereo: Speakers" --node-nickname "alsa_output.usb-SteelSeries_SteelSeries_Arctis_5_00000000-00.analog-chat:  Chat" --node-nickname "alsa_output.usb-SteelSeries_SteelSeries_Arctis_5_00000000-00.analog-game:  Game" --node-nickname "alsa_output.pci-0000_06_00.1.hdmi-stereo: Monitor" --node-nickname "alsa_output.pci-0000_08_00.4.analog-stereo: Speakers" --format '$VOL_ICON' listen
click-middle = exec pavucontrol &
click-left = pulseaudio-control togmute
click-right = pulseaudio-control next-sink
scroll-up = pulseaudio-control --volume-max 100 --volume-step 20 up
scroll-down = pulseaudio-control --volume-max 100 --volume-step 20 down

[module/volume]
type = internal/pulseaudio
format-volume = <bar-volume>
format-volume-background = ${colors.background-alt}
format-volume-padding = 1
; 5 iconos unidos
label-muted = "%{T3}ﭳﭳﭳﭳﭳ%{T-}"
label-muted-foreground = ${colors.gray}
label-muted-padding = 1
bar-volume-format = %{T4}%fill%%indicator%%empty%%{F-}%{T-}
bar-volume-width = 6
bar-volume-gradient = true
bar-volume-indicator = 
bar-volume-indicator-foreground = ${colors.yellow}
bar-volume-fill = %{T4}ﭳ%{T-}
bar-volume-foreground-0 = ${colors.sig_yellow_0}
bar-volume-foreground-1 = ${colors.sig_yellow_1}
bar-volume-foreground-2 = ${colors.sig_yellow_2}
bar-volume-foreground-3 = ${colors.sig_yellow_3}
bar-volume-foreground-4 = ${colors.sig_yellow_4}
bar-volume-fill-foreground = ${colors.yellow}
bar-volume-empty = %{T3}ﭳ%{T-}
bar-volume-empty-foreground = ${colors.foreground}
click-middle = exec pavucontrol &
click-left = pulseadio-control toggle
click-right = pulseaudio-control next-sink
scroll-up = pulseaudio-control --volume-max 100 --volume-step 20 up
scroll-down = pulseaudio-control --volume-max 100 --volume-step 20 down

[module/spotify]
type = custom/script
tail = true
format-prefix = ""
format = <label>
label-padding = 1
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh
click-left = playerctl play-pause -p spotify

[module/spotify-prev]
type = custom/script
exec = echo "%{T5}%{T-}"
format = <label>
format-foreground = ${colors.foreground}
label-padding = 1
click-left = playerctl previous -p spotify

[module/spotify-next]
type = custom/script
exec = echo "%{T5}%{T-}"
format = <label>
format-foreground = ${colors.foreground}
label-padding = 1
click-left = playerctl next -p spotify

[module/date]
type = internal/date
interval = 1
date = %{T3} %{T-}%H:%M
date-alt = %{T3} %{T-}%d-%m-%Y
label = %date%
label-padding = 1
label-foreground = ${colors.foreground}

[module/wired]
type = internal/network
interface = ens33
interface-type = wired
interval = 3.0
format-connected-background = ${colors.background-alt}
format-connected-foreground = ${colors.foreground}
format-connected-padding = 1
format-connected = %{A1:~/.config/polybar/scripts/rofi-network-manager/rofi-network-manager.sh:}<label-connected>%{A}
label-connected = %{T3} %{T-} %local_ip%
format-disconnected-background = ${colors.background-alt}
format-disconnected-foreground = ${colors.foreground}
format-disconnected-padding = 1
format-disconnected = %{A1:~/.config/polybar/scripts/rofi-network-manager/rofi-network-manager.sh:}<label-disconnected>%{A}
label-disconnected = %{T3} %{T-}

[module/wireless]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 3.0
unknown-as-up = true
; Escapo los `:` del argumento con -modi con el `/`
format-connected = %{A1:rofi -show wifi -modi wifi\:iwdrofimenu:} <ramp-signal>      <label-connected>%{A}
format-connected-background = ${colors.background-alt}
format-connected-foreground = ${colors.foreground}
format-connected-padding = 1
label-connected =  %essid%  | %local_ip%
label-connected-padding = 1
format-disconnected-background = ${colors.background-alt}
format-disconnected-foreground = ${colors.foreground}
format-disconnected-padding = 1
format-disconnected = %{A1:rofi -show wifi -modi wifi\:iwdrofimenu:}<label-disconnected>%{A}
label-disconnected = %{T3} %{T-}
ramp-signal-0 = "󰤯 "
ramp-signal-1 = "󰤟 "
ramp-signal-2 = "󰤢 "
ramp-signal-3 = "󰤥 "
ramp-signal-4 = "󰤨  "

[module/memory]
type = internal/memory
interval = 3

; Labels para el texto de memory normal
label-padding = 1
label = %used%/%total%
label-foreground = ${colors.foreground}
label-background = ${colors.background-alt}

; Formats para el icono de memory normal
format = %{T4} 󰍛 %{T-} <label>
format-foreground = ${colors.selected}
format-background = ${colors.background-alt}

; Configuracion de warn
warn-percentage = 80

; Labels para el texto de memory warn
label-warn = %used%/%free%
label-warn-foreground = ${colors.red}
label-warn-background = ${colors.background-alt}

; Formats para el icono de memory warn
format-warn = %{T3} %{T-} <label-warn>
format-warn-foreground = ${colors.yellow}
format-warn-background = ${colors.background-alt}

[module/storage]
type = internal/fs
mount-0 = /
interval = 10

; Labels para el texto de storage montado
label-mounted = %mountpoint% %used%/%total%
label-mounted-foreground = ${colors.foreground}
label-mounted-background = ${colors.background-alt}
label-mounted-padding = 1

; Configuracion de warn
warn-percentage = 80

; Labels para el texto de storage desmontado
label-unmounted = %mountpoint%: No montado!
label-unmounted-foreground = ${colors.active}
label-unmounted-background = ${colors.background-alt}
label-unmounted-padding = 1

; Formats para el icono de storage montado
format-mounted = %{T3}|  %{T-} <label-mounted>
format-mounted-foreground = ${colors.selected}
format-mounted-background = ${colors.background-alt}

; Formats para el icono de storage desmontado
format-unmounted = %{T3}|  %{T-} <label-unmounted>
format-unmounted-foreground = ${colors.selected}
format-unmounted-background = ${colors.background-alt}

[module/cava]
type = custom/script
tail = true
exec = ~/.config/polybar/scripts/cava.sh
format = <label>
format-font = 1
label = %output%
label-foreground = ${colors.foreground}
label-background = ${colors.background-alt}
label-padding = 1

[module/calendar]
type = custom/script
# necesariamente para que aparezca ya que debe haber minimo un comando en un custom/script
exec = echo " " 
label = %{T3} %{T-}
label-padding = 1
label-font = 9
click-left = ~/.config/polybar/scripts/calendar curr
scroll-up = ~/.config/polybar/scripts/calendar next
scroll-down = ~/.config/polybar/scripts/calendar prev
format-background = ${colors.background-alt}
format-foreground = ${colors.foreground}

[module/battery]
type = internal/battery
full-at = 100
battery = BAT0
adapter = ADP1
poll-interval = 5
time-format = %H:%M
 
format-charging = <animation-charging><label-charging>   
format-discharging = <ramp-capacity><label-discharging>  

label-charging = " %percentage%%  "
label-charging-foreground = ${colors.foreground}
label-discharging = " %percentage%%  "
label-discharging-foreground = ${colors.foreground}
label-charging-background = ${colors.background-alt}
label-discharging-background  = ${colors.background-alt}
format-charging-background  = ${colors.background-alt}
format-discharging-background  = ${colors.background-alt}

label-full = %{T5}󱊦 %{T-} 100%
format-full-foreground = ${colors.foreground}

ramp-capacity-0 = %{T5}󰂎%{T-}
ramp-capacity-1 = %{T5}󱊡%{T-}
ramp-capacity-2 = %{T5}󱊢%{T-}
ramp-capacity-3 = %{T5}󱊣%{T-}
ramp-capacity-foreground = ${colors.foreground}

animation-charging-0 = %{T5}󰢟 %{T-}
animation-charging-1 = %{T5}󱊤 %{T-}
animation-charging-2 = %{T5}󱊥 %{T-}
animation-charging-3 = %{T5}󱊦 %{T-}
animation-charging-framerate = 600
animation-charging-foreground = ${colors.foreground}
animation-charging-background = ${colors.background-alt}

animation-discharging-0= %{T5}󱊣%{T-}
animation-discharging-1= %{T5}󱊢%{T-}
animation-discharging-2= %{T5}󱊡%{T-}
animation-discharging-3= %{T5}󰂎%{T-}
animation-discharging-framerate = 500
animation-discharging-foreground = ${colors.foreground}
